import { auth } from '@support/desktop/Authorization'
import { prof } from '@support/desktop/Profile'
import { bank } from '@support/desktop/Banking'

describe('Withdrawal', () => {
  it('C1086785 - RUB - вывод средств на карту ', function () {
    auth.login()
    prof.withdrawal('Вывод средств')
    prof.credit_card_number()
    prof.withdrawal_number_(100)
    prof.withdrawal_button()
    bank.assert_witdrawal()
  })
  it('C1086789 - RUB - вывод средств на Qiwi ', function () {
    auth.login()
    prof.withdrawal('Вывод средств')
    prof.deposit_change()
    prof.deposit_change_switch('QIWI-кошелек')
    prof.number_phone('+79993454343')
    prof.withdrawal_number_(10)
    prof.withdrawal_button()
    bank.assert_witdrawal()
  })
  it('C1086792 - RUB - вывод средств на Webmoney WMZ ', function () {
    auth.login()
    prof.withdrawal('Вывод средств')
    prof.deposit_change()
    prof.deposit_change_switch('WebMoney WMZ')
    prof.number_phone('Z123456789012')
    prof.withdrawal_number_(10)
    prof.withdrawal_button()
    bank.assert_witdrawal()
  })
  it('C1086787 - RUB - вывод средств на Яндекс деньги ', function () {
    auth.login()
    prof.withdrawal('Вывод средств')
    prof.deposit_change()
    prof.deposit_change_switch('Яндекс.Деньги')
    prof.number_phone('410010101021023')
    prof.withdrawal_number_(100)
    prof.withdrawal_button()
    bank.assert_witdrawal()
  })
  it('C1086793 - RUB - вывод средств на AdvCash ', function () {
    auth.login()
    prof.withdrawal('Вывод средств')
    prof.deposit_change()
    prof.deposit_change_switch('AdvCash')
    prof.number_phone('lina.solodova@gmail.com')
    prof.withdrawal_number_(10)
    prof.withdrawal_button()
    bank.assert_witdrawal()
  })
  it('C1086805- EUR - вывод средств на карту ', function () {
    auth.login()
    prof.withdrawal('Вывод средств')
    cy.contains('EUR')
            .click()
    prof.credit_card_number()
    prof.withdrawal_number_EUR()
    prof.withdrawal_button()
    bank.assert_witdrawal()
  })
  it('C1086795- USD - вывод средств на карту ', function () {
    auth.login()
    prof.withdrawal('Вывод средств')
    cy.contains('USD')
            .click()
    prof.credit_card_number()
    prof.withdrawal_number_EUR()
    prof.withdrawal_button()
    bank.assert_witdrawal()
  })
  it('C1647885- EUR - вывод средств на Qiwi ', function () {
    auth.login()
    prof.withdrawal('Вывод средств')
    cy.contains('EUR')
            .click()
    prof.deposit_change()
    prof.deposit_change_switch('QIWI-кошелек')
    prof.number_phone('+79993454343')
    prof.withdrawal_number_EUR()
    prof.withdrawal_button()
    bank.assert_witdrawal()
  })
  it('C1647884- USD - вывод средств на Qiwi ', function () {
    auth.login()
    prof.withdrawal('Вывод средств')
    cy.contains('USD')
            .click()
    prof.deposit_change()
    prof.deposit_change_switch('QIWI-кошелек')
    prof.number_phone('+79993454343')
    prof.withdrawal_number_EUR()
    prof.withdrawal_button()
    bank.assert_witdrawal()
  })
})
